# ─────────────────────────────────────────────────────────────────────────────
# Host-specific overrides for hyperia
# ─────────────────────────────────────────────────────────────────────────────
font-size = 12
