# ─────────────────────────────────────────────────────────────────────────────
# macOS Font Settings
# ─────────────────────────────────────────────────────────────────────────────
font-family = PragmataProMonoLiga Nerd Font Mono
font-family-bold = PragmataProMonoLiga Nerd Font Mono
font-family-italic = PragmataProMonoLiga Nerd Font Mono
font-family-bold-italic = PragmataProMonoLiga Nerd Font Mono
