---
extends: default

rules:
  line-length:
    max: 120
    level: error
  document-start: disable # Don't require --- at start
  comments:
    min-spaces-from-content: 1
    require-starting-space: false # Allow compact comments like #comment
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
  empty-lines:
    max: 2
    max-start: 0
    max-end: 1
