- defaults:
    link:
      relink: true

- clean: ['~']

- shell:
    - curl http://storage.googleapis.com/git-repo-downloads/repo > bin/repo
    - chmod +x bin/repo
    - vim-addons install powerline
    - systemctl --user start powerline-daemon
    - vam install youcompleteme
    - mkdir -p ~/.config/nvim

- link:
    ~/.bashrc.local:
    ~/.config/nvim/init.vim: nvim/init.vim
    ~/.fonts:
    ~/.gitconfig:
    ~/.screenrc:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.Xmodmap:
    ~/bin: bin

- shell:
    - fc-cache -f
    - fzf/install --no-update-rc --key-bindings --completion
