- defaults:
    link:
      relink: true

- clean: ['~']

- shell:
    - mkdir -p ~/.config/nvim

- link:
    ~/.bashrc.local:
    ~/.rc.local:
    ~/.config/nvim/init.vim: nvim/init.vim
    ~/.fonts:
    ~/.gitconfig:
    ~/.screenrc:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.Xmodmap:
    ~/bin: bin

- shell:
    - fc-cache -f
    - curl http://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    - chmod +x ~/bin/repo
    - vim-addons install powerline
    - vam install youcompleteme
    - grep -qxF 'source ~/.bashrc.local' ~/.bashrc || echo 'source ~/.bashrc.local' >> ~/.bashrc
