- defaults:
    link:
      relink: true

- clean: ["~"]

- shell:
    - if [ -d ~/dev/dotfiles-private ]; then ln -sf ~/dev/dotfiles-private/fonts/Pragmata\ Pro fonts/;fi

- link:
    ~/.bashrc.local: bash/bashrc.local
    ~/.config/lsd: lsd
    ~/.config/bat: bat
    ~/.fonts:
    ~/.gitconfig:
    ~/.tmux.conf:
    ~/.dircolors:
    ~/.zshrc: zsh/zshrc
    ~/.config/nvim: nvim
    ~/bin: bin

- shell:
    - fc-cache -f

- shell:
    - curl http://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    - chmod +x ~/bin/repo

- shell:
    - command: |
        # Install Rust toolchain and CLI tools
        rustup toolchain install stable
        # Add cargo to PATH (apt rustup doesn't create ~/.cargo/env)
        export PATH="$HOME/.cargo/bin:$PATH"
        if command -v cargo &> /dev/null; then
          echo "📦 Installing Rust CLI tools from cargo-tools.txt..."
          grep -v '^#\|^$' cargo-tools.txt | sed 's/#.*//' | xargs cargo install
        fi
      stderr: true
      stdout: true
      description: "Installing Rust toolchain + CLI tools"

- shell:
    - mkdir -p ~/.config/fastfetch
- link:
    ~/.config/fastfetch/config.jsonc: fastfetch/config.jsonc

- shell:
    - mkdir -p ~/.tmux/plugins
- link:
    ~/.tmux/plugins/tpm: tpm

- shell:
    - mkdir -p ~/.config/procs
- link:
    ~/.config/procs/config.toml: procs/config.toml

- shell:
    - mkdir -p ~/.config/starship
- link:
    ~/.config/starship.toml: starship/starship.toml

- shell:
    - mkdir -p ~/.warp/themes
- link:
    ~/.warp/themes/lilac.yaml: warp/themes/lilac.yaml

- shell:
    - mkdir -p "$HOME/Library/Application Support/com.mitchellh.ghostty"
- link:
    ~/Library/Application Support/com.mitchellh.ghostty/config: ghostty/config

- shell:
    - command: mkdir -p ~/dev/go && GOPATH=~/dev/go go install github.com/junegunn/fzf@latest
      stderr: true
      stdout: true
      quiet: false
      description: Installing fzf from source

- shell:
    - command: |
        # Install proto version manager if not present
        if ! command -v proto &> /dev/null; then
          echo "✨ Installing proto version manager..."
          curl -fsSL https://moonrepo.dev/install/proto.sh | bash -s -- --yes
          export PROTO_HOME="$HOME/.proto"
          export PATH="$PROTO_HOME/shims:$PROTO_HOME/bin:$PATH"
        fi
        # Install node and npm via proto
        if command -v proto &> /dev/null; then
          echo "📦 Setting up node and npm via proto..."
          proto install node lts
          proto install npm
          # Pin versions globally (writes to ~/.prototools)
          proto pin node lts
          proto pin npm bundled
        fi
      stderr: true
      stdout: true
      description: "Installing proto + node/npm"

- shell:
    - mkdir -p ~/.claude
- link:
    ~/.claude/settings.json: claude/settings.json
    ~/.claude/statusline-command.sh: claude/statusline-command.sh

- shell:
    - mkdir -p ~/.config/atuin/themes
- link:
    ~/.config/atuin/config.toml: atuin/config.toml
    ~/.config/atuin/themes/silkcircuit.toml: atuin/themes/silkcircuit.toml

- shell:
    - mkdir -p ~/.config/fontconfig
    - mkdir -p ~/.config/ghostty
- link:
    ~/.config/fontconfig/fonts.conf: fonts/fonts.conf
    ~/.config/ghostty/linux.conf: ghostty/linux.conf
