- defaults:
    link:
      relink: true

- clean: ['~']

- shell:
    - mkdir -p ~/.config/nvim

- link:
    ~/.bashrc.local:
    ~/.rc.local:
    ~/.config/lsd: lsd
    ~/.fonts:
    ~/.gitconfig:
    ~/.screenrc:
    ~/.tmux.conf:
    ~/.dircolors:
    ~/.vim:
    ~/.vimrc:
    ~/.zshrc: zsh/zshrc
    ~/.config/nvim: nvim
    ~/bin: bin

- shell:
    - fc-cache -f

- shell:
    - curl http://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    - chmod +x ~/bin/repo

- shell:
    - cargo install lsd
