- defaults:
    link:
      relink: true

- clean: ['~']

- shell:
    - if [ -d ~/dev/dotfiles-private ]; then ln -sf ~/dev/dotfiles-private/fonts/Pragmata\ Pro fonts/;fi

- link:
    ~/.bashrc.local:
    ~/.rc.local:
    ~/.config/lsd: lsd
    ~/.fonts:
    ~/.gitconfig:
    ~/.tmux.conf:
    ~/.dircolors:
    ~/.zshrc: zsh/zshrc
    ~/.config/nvim: nvim
    ~/bin: bin

- shell:
    - fc-cache -f

- shell:
    - curl http://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
    - chmod +x ~/bin/repo

- shell:
    - cargo install lsd

- shell:
    - cargo install macchina
    - mkdir -p ~/.config/macchina/themes
- link:
    ~/.config/macchina/themes/elektra.toml: elektra/elektra.toml
    ~/.config/macchina/ubuntu-ascii.txt: elektra/ubuntu-ascii.txt

- shell:
    - mkdir -p ~/.tmux/plugins
- link:
    ~/.tmux/plugins/tpm: tpm

- shell:
    - cargo install starship
    - mkdir -p ~/.config/starship
- link:
    ~/.config/starship.toml: starship/starship.toml


