#!/usr/bin/env sh
# skhd configuration for use with yabai window manager

# Reload yabai and skhd
ctrl + alt + cmd - r : \
  launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"
skhd --reload

# Change focus
alt - h : yabai -m window --focus west
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - l : yabai -m window --focus east

# Swap windows
shift + alt - h : yabai -m window --swap west
shift + alt - j : yabai -m window --swap south
shift + alt - k : yabai -m window --swap north
shift + alt - l : yabai -m window --swap east

# Move windows
shift + cmd - h : yabai -m window --warp west
shift + cmd - j : yabai -m window --warp south
shift + cmd - k : yabai -m window --warp north
shift + cmd - l : yabai -m window --warp east

# Balance size of windows
shift + alt - 0 : yabai -m space --balance

# Fast focus desktop
alt - 1 : yabai -m space --focus 1
alt - 2 : yabai -m space --focus 2
alt - 3 : yabai -m space --focus 3
alt - 4 : yabai -m space --focus 4
alt - 5 : yabai -m space --focus 5
alt - 6 : yabai -m space --focus 6
alt - 7 : yabai -m space --focus 7
alt - 8 : yabai -m space --focus 8
alt - 9 : yabai -m space --focus 9

# Create and destroy spaces
shift + cmd - n : yabai -m space --create
shift + cmd - d : yabai -m space --destroy

# Send window to desktop and follow focus
shift + cmd - 1 : yabai -m window --space 1
yabai -m space --focus 1
shift + cmd - 2 : yabai -m window --space 2
yabai -m space --focus 2
shift + cmd - 3 : yabai -m window --space 3
yabai -m space --focus 3
shift + cmd - 4 : yabai -m window --space 4
yabai -m space --focus 4
shift + cmd - 5 : yabai -m window --space 5
yabai -m space --focus 5
shift + cmd - 6 : yabai -m window --space 6
yabai -m space --focus 6
shift + cmd - 7 : yabai -m window --space 7
yabai -m space --focus 7
shift + cmd - 8 : yabai -m window --space 8
yabai -m space --focus 8
shift + cmd - 9 : yabai -m window --space 9
yabai -m space --focus 9

# Resize windows
ctrl + alt - h : yabai -m window --resize left:-20:0
ctrl + alt - j : yabai -m window --resize bottom:0:20
ctrl + alt - k : yabai -m window --resize top:0:-20
ctrl + alt - l : yabai -m window --resize right:20:0

# Float / Unfloat window
shift + alt - space : \
  yabai -m window --toggle float
yabai -m window --toggle border

# Toggle window fullscreen
alt - f : yabai -m window --toggle zoom-fullscreen

# Toggle window native fullscreen
shift + alt - f : yabai -m window --toggle native-fullscreen

# Toggle window split type
alt - e : yabai -m window --toggle split

# Change layout of desktop
ctrl + alt - b : yabai -m space --layout bsp
ctrl + alt - f : yabai -m space --layout float
ctrl + alt - s : yabai -m space --layout stack

# Open terminal quickly
cmd - return : open -a iTerm
