---@type LazySpec
return {
  "pwntester/octo.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "nvim-telescope/telescope.nvim",
    "nvim-tree/nvim-web-devicons",
  },
  cmd = "Octo",
  event = { { event = "BufReadCmd", pattern = "octo://*" } },
  opts = {
    -- Use telescope for picker
    picker = "telescope",
    -- Enable builtin viewer
    enable_builtin = true,
    -- Default to projects view
    default_to_projects_v2 = true,
    -- Always use local files for reviews
    always_select_remote_on_create = false,
    -- Snippet engine
    snippet_context_lines = 4,
    -- GitHub CLI command
    gh_cmd = "gh",
    -- Timeout for requests
    timeout = 5000,
    -- UI customization
    ui = {
      use_signcolumn = true,
    },
    -- Issue/PR templates
    issues = {
      order_by = {
        field = "UPDATED_AT",
        direction = "DESC",
      },
    },
    pull_requests = {
      order_by = {
        field = "UPDATED_AT",
        direction = "DESC",
      },
      always_select_remote_on_create = false,
    },
    -- File panel configuration
    file_panel = {
      size = 10,
      use_icons = true,
    },
    -- Mappings
    mappings_disable_default = false,
    mappings = {
      issue = {
        close_issue = { lhs = "<localleader>ic", desc = "Close issue" },
        reopen_issue = { lhs = "<localleader>io", desc = "Reopen issue" },
        list_issues = { lhs = "<localleader>il", desc = "List open issues" },
        reload = { lhs = "<C-r>", desc = "Reload issue" },
        open_in_browser = { lhs = "<C-b>", desc = "Open issue in browser" },
        copy_url = { lhs = "<C-y>", desc = "Copy issue URL" },
        add_assignee = { lhs = "<localleader>aa", desc = "Add assignee" },
        remove_assignee = { lhs = "<localleader>ad", desc = "Remove assignee" },
        create_label = { lhs = "<localleader>lc", desc = "Create label" },
        add_label = { lhs = "<localleader>la", desc = "Add label" },
        remove_label = { lhs = "<localleader>ld", desc = "Remove label" },
        goto_issue = { lhs = "<localleader>gi", desc = "Navigate to issue" },
        add_comment = { lhs = "<localleader>ca", desc = "Add comment" },
        delete_comment = { lhs = "<localleader>cd", desc = "Delete comment" },
        next_comment = { lhs = "]c", desc = "Go to next comment" },
        prev_comment = { lhs = "[c", desc = "Go to previous comment" },
        react_hooray = { lhs = "<localleader>rp", desc = "Add 🎉 reaction" },
        react_heart = { lhs = "<localleader>rh", desc = "Add ❤️ reaction" },
        react_eyes = { lhs = "<localleader>re", desc = "Add 👀 reaction" },
        react_thumbs_up = { lhs = "<localleader>r+", desc = "Add 👍 reaction" },
        react_thumbs_down = { lhs = "<localleader>r-", desc = "Add 👎 reaction" },
        react_rocket = { lhs = "<localleader>rr", desc = "Add 🚀 reaction" },
        react_laugh = { lhs = "<localleader>rl", desc = "Add 😄 reaction" },
        react_confused = { lhs = "<localleader>rc", desc = "Add 😕 reaction" },
      },
      pull_request = {
        checkout_pr = { lhs = "<localleader>po", desc = "Checkout PR" },
        merge_pr = { lhs = "<localleader>pm", desc = "Merge PR" },
        squash_and_merge_pr = { lhs = "<localleader>psm", desc = "Squash and merge PR" },
        rebase_and_merge_pr = { lhs = "<localleader>prm", desc = "Rebase and merge PR" },
        list_commits = { lhs = "<localleader>pc", desc = "List PR commits" },
        list_changed_files = { lhs = "<localleader>pf", desc = "List PR changed files" },
        show_pr_diff = { lhs = "<localleader>pd", desc = "Show PR diff" },
        add_reviewer = { lhs = "<localleader>va", desc = "Add reviewer" },
        remove_reviewer = { lhs = "<localleader>vd", desc = "Remove reviewer" },
        close_issue = { lhs = "<localleader>ic", desc = "Close PR" },
        reopen_issue = { lhs = "<localleader>io", desc = "Reopen PR" },
        list_issues = { lhs = "<localleader>il", desc = "List open PRs" },
        reload = { lhs = "<C-r>", desc = "Reload PR" },
        open_in_browser = { lhs = "<C-b>", desc = "Open PR in browser" },
        copy_url = { lhs = "<C-y>", desc = "Copy PR URL" },
        goto_file = { lhs = "gf", desc = "Go to file" },
        add_assignee = { lhs = "<localleader>aa", desc = "Add assignee" },
        remove_assignee = { lhs = "<localleader>ad", desc = "Remove assignee" },
        create_label = { lhs = "<localleader>lc", desc = "Create label" },
        add_label = { lhs = "<localleader>la", desc = "Add label" },
        remove_label = { lhs = "<localleader>ld", desc = "Remove label" },
        goto_issue = { lhs = "<localleader>gi", desc = "Navigate to PR" },
        add_comment = { lhs = "<localleader>ca", desc = "Add comment" },
        delete_comment = { lhs = "<localleader>cd", desc = "Delete comment" },
        next_comment = { lhs = "]c", desc = "Go to next comment" },
        prev_comment = { lhs = "[c", desc = "Go to previous comment" },
        react_hooray = { lhs = "<localleader>rp", desc = "Add 🎉 reaction" },
        react_heart = { lhs = "<localleader>rh", desc = "Add ❤️ reaction" },
        react_eyes = { lhs = "<localleader>re", desc = "Add 👀 reaction" },
        react_thumbs_up = { lhs = "<localleader>r+", desc = "Add 👍 reaction" },
        react_thumbs_down = { lhs = "<localleader>r-", desc = "Add 👎 reaction" },
        react_rocket = { lhs = "<localleader>rr", desc = "Add 🚀 reaction" },
        react_laugh = { lhs = "<localleader>rl", desc = "Add 😄 reaction" },
        react_confused = { lhs = "<localleader>rc", desc = "Add 😕 reaction" },
        review_start = { lhs = "<localleader>vs", desc = "Start review" },
        review_resume = { lhs = "<localleader>vr", desc = "Resume review" },
      },
      review_thread = {
        goto_issue = { lhs = "<localleader>gi", desc = "Navigate to PR" },
        add_comment = { lhs = "<localleader>ca", desc = "Add comment" },
        add_suggestion = { lhs = "<localleader>sa", desc = "Add suggestion" },
        delete_comment = { lhs = "<localleader>cd", desc = "Delete comment" },
        next_comment = { lhs = "]c", desc = "Go to next comment" },
        prev_comment = { lhs = "[c", desc = "Go to previous comment" },
        select_next_entry = { lhs = "]q", desc = "Move to next thread" },
        select_prev_entry = { lhs = "[q", desc = "Move to previous thread" },
        select_first_entry = { lhs = "[Q", desc = "Move to first thread" },
        select_last_entry = { lhs = "]Q", desc = "Move to last thread" },
        close_review_tab = { lhs = "<C-c>", desc = "Close review tab" },
        react_hooray = { lhs = "<localleader>rp", desc = "Add 🎉 reaction" },
        react_heart = { lhs = "<localleader>rh", desc = "Add ❤️ reaction" },
        react_eyes = { lhs = "<localleader>re", desc = "Add 👀 reaction" },
        react_thumbs_up = { lhs = "<localleader>r+", desc = "Add 👍 reaction" },
        react_thumbs_down = { lhs = "<localleader>r-", desc = "Add 👎 reaction" },
        react_rocket = { lhs = "<localleader>rr", desc = "Add 🚀 reaction" },
        react_laugh = { lhs = "<localleader>rl", desc = "Add 😄 reaction" },
        react_confused = { lhs = "<localleader>rc", desc = "Add 😕 reaction" },
      },
      submit_win = {
        approve_review = { lhs = "<C-a>", desc = "Approve review" },
        comment_review = { lhs = "<C-m>", desc = "Comment review" },
        request_changes = { lhs = "<C-r>", desc = "Request changes" },
        close_review_tab = { lhs = "<C-c>", desc = "Close review tab" },
      },
      review_diff = {
        submit_review = { lhs = "<localleader>vs", desc = "Submit review" },
        discard_review = { lhs = "<localleader>vd", desc = "Discard review" },
        add_review_comment = { lhs = "<localleader>ca", desc = "Add line comment" },
        add_review_suggestion = { lhs = "<localleader>sa", desc = "Add line suggestion" },
        focus_files = { lhs = "<localleader>e", desc = "Focus changed files" },
        toggle_files = { lhs = "<localleader>b", desc = "Toggle changed files" },
        next_thread = { lhs = "]t", desc = "Move to next thread" },
        prev_thread = { lhs = "[t", desc = "Move to previous thread" },
        select_next_entry = { lhs = "]q", desc = "Move to next changed file" },
        select_prev_entry = { lhs = "[q", desc = "Move to previous changed file" },
        select_first_entry = { lhs = "[Q", desc = "Move to first changed file" },
        select_last_entry = { lhs = "]Q", desc = "Move to last changed file" },
        close_review_tab = { lhs = "<C-c>", desc = "Close review tab" },
        toggle_viewed = { lhs = "<localleader><space>", desc = "Toggle file viewed" },
        goto_file = { lhs = "gf", desc = "Go to file" },
      },
      file_panel = {
        submit_review = { lhs = "<localleader>vs", desc = "Submit review" },
        discard_review = { lhs = "<localleader>vd", desc = "Discard review" },
        next_entry = { lhs = "j", desc = "Move to next changed file" },
        prev_entry = { lhs = "k", desc = "Move to previous changed file" },
        select_entry = { lhs = "<cr>", desc = "Show file diff" },
        refresh_files = { lhs = "R", desc = "Refresh changed files" },
        focus_files = { lhs = "<localleader>e", desc = "Focus changed files" },
        toggle_files = { lhs = "<localleader>b", desc = "Toggle changed files" },
        select_next_entry = { lhs = "]q", desc = "Move to next changed file" },
        select_prev_entry = { lhs = "[q", desc = "Move to previous changed file" },
        select_first_entry = { lhs = "[Q", desc = "Move to first changed file" },
        select_last_entry = { lhs = "]Q", desc = "Move to last changed file" },
        close_review_tab = { lhs = "<C-c>", desc = "Close review tab" },
        toggle_viewed = { lhs = "<localleader><space>", desc = "Toggle file viewed" },
      },
    },
  },
  keys = {
    { "<leader>go", "<cmd>Octo<cr>", desc = "Octo" },
    { "<leader>goi", "<cmd>Octo issue list<cr>", desc = "List issues" },
    { "<leader>goI", "<cmd>Octo issue search<cr>", desc = "Search issues" },
    { "<leader>gop", "<cmd>Octo pr list<cr>", desc = "List PRs" },
    { "<leader>goP", "<cmd>Octo pr search<cr>", desc = "Search PRs" },
    { "<leader>gor", "<cmd>Octo repo list<cr>", desc = "List repos" },
    { "<leader>goS", "<cmd>Octo search<cr>", desc = "Search" },
    { "<leader>goa", "<cmd>Octo actions<cr>", desc = "Run action" },
  },
}
