-- Trouble.nvim - A pretty diagnostics, references, telescope results, quickfix and location list
-- Provides a VSCode-like problems window for diagnostics

---@type LazySpec
return {
  "folke/trouble.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  cmd = { "Trouble" },
  opts = {
    modes = {
      diagnostics = {
        mode = "diagnostics",
        preview = {
          type = "split",
          relative = "win",
          position = "right",
          size = 0.3,
        },
      },
    },
    -- Modern Trouble.nvim configuration (v3+)
    position = "right",
    width = 50,
    height = 10,
    padding = true,
    focus = false,
    follow = true,
    restore = true,
    keys = {
      ["<cr>"] = "jump_close",
      ["<2-leftmouse>"] = "jump_close",
      ["<c-s>"] = "jump_split",
      ["<c-v>"] = "jump_vsplit",
      ["<c-t>"] = "jump_tab",
      q = "close",
      o = "jump_close",
      ["<esc>"] = "close",
      r = "refresh",
      R = "refresh",
      ["?"] = "help",
      k = "prev",
      j = "next",
      ["[["] = "prev",
      ["]]"] = "next",
      ["<tab>"] = "fold_toggle",
      ["<s-tab>"] = "fold_toggle_recursive",
      zr = "fold_open_all",
      zm = "fold_close_all",
      zR = "fold_open_all",
      zM = "fold_close_all",
      ["<c-q>"] = "send_to_qflist",
      ["<leader>q"] = "send_to_qflist",
    },
    icons = {
      indent = {
        top = "│ ",
        middle = "├╴",
        last = "└╴",
        fold_open = " ",
        fold_closed = " ",
        ws = "  ",
      },
      folder_closed = " ",
      folder_open = " ",
      kinds = {
        Array = " ",
        Boolean = "󰨙 ",
        Class = " ",
        Constant = "󰏿 ",
        Constructor = " ",
        Enum = " ",
        EnumMember = " ",
        Event = " ",
        Field = " ",
        File = " ",
        Function = "󰊕 ",
        Interface = " ",
        Key = " ",
        Method = "󰊕 ",
        Module = " ",
        Namespace = "󰦮 ",
        Null = " ",
        Number = "󰎠 ",
        Object = " ",
        Operator = " ",
        Package = " ",
        Property = " ",
        String = " ",
        Struct = "󰆼 ",
        TypeParameter = " ",
        Variable = "󰀫 ",
      },
    },
  },
  keys = {
    -- Add keybindings to toggle the problems window
    {
      "<leader>lD",
      "<cmd>Trouble diagnostics toggle<cr>",
      desc = "Diagnostics Panel (Trouble)",
    },
    {
      "<leader>ld",
      "<cmd>Trouble diagnostics toggle filter.buf=0<cr>",
      desc = "Buffer Diagnostics Panel (Trouble)",
    },
    {
      "<leader>ls",
      "<cmd>Trouble symbols toggle focus=false<cr>",
      desc = "Symbols Outline (Trouble)",
    },
    {
      "<leader>lT",
      "<cmd>Trouble lsp toggle focus=false win.position=right<cr>",
      desc = "LSP References/Definitions (Trouble)",
    },
    -- Alternative mapping for quick access
    {
      "<C-\\>",
      "<cmd>Trouble diagnostics toggle<cr>",
      desc = "Toggle Problems Panel",
    },
  },
}
