# Zsh-specific settings and configurations

# History settings
setopt share_history
setopt hist_ignore_all_dups
setopt inc_append_history

HISTSIZE=50000
SAVEHIST=50000
HISTFILE=~/.zsh_history

# Normalize path to use ~ for home directory
normalize_path() {
    echo "${PWD/#$HOME/~}"
}

# Set the terminal title to user@host: normalized_path
precmd() {
    local normalized_path=$(normalize_path)
    echo -ne "\033]0;${USER}@${HOSTNAME}: ${normalized_path}\007"
}

# Source custom configurations
source ~/dev/dotfiles/zsh/aliases.zsh
source ~/dev/dotfiles/zsh/completion.zsh

# Source system-provided utilities
source /usr/share/doc/fzf/examples/key-bindings.zsh
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /etc/zsh_command_not_found

# Load shell utilities and extensions
source ~/dev/dotfiles/sh/shell-common.sh
