name: ⚡ Lint & Format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # → Comprehensive linting and formatting checks
  lint-and-format:
    name: » Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - name: → Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false # Don't need submodules for linting

      - name: → Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: → Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: → Install shellcheck
        uses: taiki-e/install-action@v2
        with:
          tool: shellcheck

      - name: → Install shfmt
        uses: taiki-e/install-action@v2
        with:
          tool: shfmt

      - name: → Install selene
        uses: taiki-e/install-action@v2
        with:
          tool: selene

      - name: → Install stylua
        uses: taiki-e/install-action@v2
        with:
          tool: stylua

      - name: → Install Python linters
        run: pip install --user yamllint beautysh

      - name: → Install markdownlint
        run: npm install -g markdownlint-cli

      - name: → Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh

      - name: → Run all linters
        run: |
          echo "» Running comprehensive linting..."
          make lint

      - name: → Check formatting
        run: |
          echo "» Checking code formatting..."
          make format

          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::Formatting issues found! Run 'make format' locally to fix."
            echo "! Files with formatting issues:"
            git status --porcelain
            echo ""
            echo "! Diff:"
            git diff
            exit 1
          fi

          echo "√ All files are properly formatted and linted!"
